In [1]:
from sklearn.datasets import fetch_openml
import pandas as pd
mnist = fetch_openml('mnist_784', version=1, parser = 'auto')



In [2]:


mnist.target

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [3]:
import numpy as np
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [4]:
print(mnist.keys())


dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])


In [5]:
mnist.data.iloc[0]

pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
           ..
pixel780    0
pixel781    0
pixel782    0
pixel783    0
pixel784    0
Name: 0, Length: 784, dtype: int64

In [6]:
mnist.categories

In [7]:
mnist.target

0        5
1        0
2        4
3        1
4        9
        ..
69995    2
69996    3
69997    4
69998    5
69999    6
Name: class, Length: 70000, dtype: category
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [8]:
X = pd.DataFrame(mnist.data)
X

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995       0       0       0       0       0       0       0       0       0   
69996       0       0       0       0       0       0       0       0       0   
69997       0       0       0       0       0       0       0       0       0   
69998       0       0       0       0       0       0       0       0       0   
69999       0       0       0       0       0       0       0       0       0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0            0  ...         0         0         0         0         0   
1            0  ...         0         0         0         0         0   
2            0  ...         0         0         0         0         0   
3            0  ...         0         0         0         0         0   
4            0  ...         0         0         0         0         0   
...        ...  ...       ...       ...       ...       ...       ...   
69995        0  ...         0         0         0         0         0   
69996        0  ...         0         0         0         0         0   
69997        0  ...         0         0         0         0         0   
69998        0  ...         0         0         0         0         0   
69999        0  ...         0         0         0         0         0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
69995         0         0         0         0         0  
69996         0         0         0         0         0  
69997         0         0         0         0         0  
69998         0         0         0         0         0  
69999         0         0         0         0         0  

[70000 rows x 784 columns]

In [9]:
y = pd.DataFrame(mnist.target)
y

class
0         5
1         0
2         4
3         1
4         9
...     ...
69995     2
69996     3
69997     4
69998     5
69999     6

[70000 rows x 1 columns]

In [10]:
y = y.sort_values(by=['class'])
y

class
34999     0
56424     0
56419     0
16705     0
56415     0
...     ...
13687     9
42651     9
58914     9
13678     9
58529     9

[70000 rows x 1 columns]

In [11]:
y.index

Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388, 56429,
       ...
       13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678, 58529],
      dtype='int64', length=70000)

In [12]:
new_index = y.index

In [13]:
X = X.reindex(new_index)
X

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999       0       0       0       0       0       0       0       0       0   
56424       0       0       0       0       0       0       0       0       0   
56419       0       0       0       0       0       0       0       0       0   
16705       0       0       0       0       0       0       0       0       0   
56415       0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687       0       0       0       0       0       0       0       0       0   
42651       0       0       0       0       0       0       0       0       0   
58914       0       0       0       0       0       0       0       0       0   
13678       0       0       0       0       0       0       0       0       0   
58529       0       0       0       0       0       0       0       0       0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999        0  ...         0         0         0         0         0   
56424        0  ...         0         0         0         0         0   
56419        0  ...         0         0         0         0         0   
16705        0  ...         0         0         0         0         0   
56415        0  ...         0         0         0         0         0   
...        ...  ...       ...       ...       ...       ...       ...   
13687        0  ...         0         0         0         0         0   
42651        0  ...         0         0         0         0         0   
58914        0  ...         0         0         0         0         0   
13678        0  ...         0         0         0         0         0   
58529        0  ...         0         0         0         0         0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999         0         0         0         0         0  
56424         0         0         0         0         0  
56419         0         0         0         0         0  
16705         0         0         0         0         0  
56415         0         0         0         0         0  
...         ...       ...       ...       ...       ...  
13687         0         0         0         0         0  
42651         0         0         0         0         0  
58914         0         0         0         0         0  
13678         0         0         0         0         0  
58529         0         0         0         0         0  

[70000 rows x 784 columns]

In [14]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)


(56000, 784) (56000, 1)
(14000, 784) (14000, 1)


In [15]:
data = y_train['class']
s = pd.Series(data)
s.unique()

['0', '1', '2', '3', '4', '5', '6', '7']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [16]:
data = y_test['class']
s = pd.Series(data)
s.unique()

['7', '8', '9']
Categories (10, object): ['0', '1', '2', '3', ..., '6', '7', '8', '9']

In [17]:
from sklearn.model_selection import train_test_split
X = mnist.data
y = mnist.target
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# data = y_train['class']
# s = pd.Series(data)
# s.unique().sort_values()
class_counts = y_train.value_counts().reset_index().sort_values(by='class')
class_list = class_counts['class'].tolist()
class_list

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [19]:
# data = y_test['class']
# s = pd.Series(data)
# s.unique().sort_values()
class_counts = y_test.value_counts().reset_index().sort_values(by='class')
class_list = class_counts['class'].tolist()
class_list

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [20]:
#Uczenie, jedna klasa
from sklearn.linear_model import SGDClassifier



In [21]:
y_train_0 = (y_train == '0')
y_train_0

47339    False
67456    False
12308    False
32557     True
664      False
         ...  
37194    False
6265     False
54886    False
860       True
15795     True
Name: class, Length: 56000, dtype: bool

In [22]:
y_test_0 = (y_test== '0')
y_test_0

46730    False
48393    False
41416    False
34506    False
43725    False
         ...  
21525    False
16276    False
24390    False
28061    False
63452    False
Name: class, Length: 14000, dtype: bool

In [23]:
sgd_clf = SGDClassifier(random_state=42, n_jobs = -1)
sgd_clf.fit(X_train, y_train_0)

SGDClassifier(n_jobs=-1, random_state=42)

In [24]:
some_digit = mnist.data.iloc[1]
sgd_clf.predict([some_digit])

/home/dia/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(


array([ True])

In [25]:
to_pck = []

In [26]:
from sklearn.metrics import accuracy_score
y_train_pred = sgd_clf.predict(X_train)

train_accuracy = float(accuracy_score(y_train_0, y_train_pred))
to_pck.append(train_accuracy)
to_pck

[0.9918571428571429]

In [27]:
y_test_pred = sgd_clf.predict(X_test)
test_accuracy = float (accuracy_score(y_test_0, y_test_pred))
print(type(test_accuracy))
to_pck.append(test_accuracy)
to_pck                             

<class 'float'>


[0.9918571428571429, 0.9903571428571428]

In [28]:
type(to_pck)

list

In [29]:
import pickle
with open('sgd_acc.pkl', 'wb') as f:
    pickle.dump(to_pck, f)

In [30]:
from sklearn.model_selection import cross_val_score
list = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy", n_jobs = -1)
print(list)

[0.98687523 0.98762522 0.98649952]


In [31]:
array = np.array(list)
type(array)
array.shape

(3,)

In [32]:
with open ('sgd_cva.pkl', 'wb') as f:
    pickle.dump(array,f)

In [33]:
from sklearn.model_selection import cross_val_predict
y_train_0_pred = cross_val_predict(sgd_clf, X_train, y_train_0, cv=3, n_jobs = -1)
y_train_0_pred

array([False, False, False, ..., False,  True,  True])

In [34]:
y_train_0_pred

array([False, False, False, ..., False,  True,  True])

In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_train_0, y_train_0_pred)
cm
#49966 prawidlowo uzanane za nie - 0 

array([[49966,   474],
       [  254,  5306]])

In [36]:

#zadanie ostatnie
sgd_m_clf = SGDClassifier(random_state=42,n_jobs=-1)
sgd_m_clf.fit(X_train, y_train)

SGDClassifier(n_jobs=-1, random_state=42)

In [45]:
sgd_m_clf.predict([some_digit])

/home/dia/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(


array(['0'], dtype='<U1')

In [46]:
sgd_m_clf.decision_function([some_digit]).round()

/home/dia/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(


array([[ 22816., -35703.,  -7939.,  -7341., -29374., -11887., -25407.,
        -17537.,  -7827.,  -2811.]])

In [47]:
y_test_pred = cross_val_predict(sgd_m_clf, X_test,y_test, cv=3, n_jobs=-1)

In [48]:
conf_mx = confusion_matrix(y_test, y_test_pred)
conf_mx

array([[1245,    1,    7,    8,    4,   17,   12,    4,   38,    7],
       [   0, 1541,    5,    7,    2,    5,    3,    1,   33,    3],
       [  10,   26, 1107,   36,   22,    6,   25,   18,  119,   11],
       [   4,    9,   24, 1170,    7,   46,    5,   15,  125,   28],
       [   2,    4,    7,    9, 1125,    6,   17,    9,   37,   79],
       [  15,    8,   11,   85,   21,  902,   25,    7,  172,   27],
       [  12,    6,   15,    4,   12,   25, 1284,    1,   35,    2],
       [   7,    4,   12,   17,   23,    4,    0, 1315,   33,   88],
       [   6,   29,   15,   32,    8,   37,   12,   10, 1169,   39],
       [   6,   10,    6,   22,   46,   10,    0,   35,   50, 1235]])

In [49]:
conf_mx.shape

(10, 10)

In [50]:
array_conf = np.array(conf_mx).reshape(10,10)
array_conf

array([[1245,    1,    7,    8,    4,   17,   12,    4,   38,    7],
       [   0, 1541,    5,    7,    2,    5,    3,    1,   33,    3],
       [  10,   26, 1107,   36,   22,    6,   25,   18,  119,   11],
       [   4,    9,   24, 1170,    7,   46,    5,   15,  125,   28],
       [   2,    4,    7,    9, 1125,    6,   17,    9,   37,   79],
       [  15,    8,   11,   85,   21,  902,   25,    7,  172,   27],
       [  12,    6,   15,    4,   12,   25, 1284,    1,   35,    2],
       [   7,    4,   12,   17,   23,    4,    0, 1315,   33,   88],
       [   6,   29,   15,   32,    8,   37,   12,   10, 1169,   39],
       [   6,   10,    6,   22,   46,   10,    0,   35,   50, 1235]])

In [51]:
with open('sgd_cmx.pkl', 'wb') as f:
    pickle.dump(array_conf, f)